-- Services.
local CollectionService = game:GetService("CollectionService")
local RunService = game:GetService("RunService")

-- Directories.
local root = script.Parent
local data = root.Data
local utilities = root.Utilities

-- Easing functions.
local easingFunctions = require(utilities.EasingFunctions)

-- Updation functions.
local getUpdateFunctions = require(utilities.UpdateFunctions)

-- Signal library.
local Signal = nil
if plugin then
	for _, instance in plugin:GetDescendants() do
		if instance:HasTag("Signal") then
			Signal = require(instance)
			if type(Signal) == "table" and Signal.new then Signal = Signal.new end
			break
		end
	end
	if not Signal then error("Could not find a signal library.") end
else
	Signal = CollectionService:GetTagged("Signal")[1]
	if not Signal then error("Could not find a signal library.") end
	Signal = require(Signal)
	if type(Signal) == "table" and Signal.new then Signal = Signal.new end
end

-- Attempt to find the plugin object.
local plugin = script:FindFirstAncestorOfClass("Plugin")

-- Network packets and Roblox API map.
local packets = nil
local apiMap = nil
if plugin then
	for _, instance in plugin:GetDescendants() do
		if instance:HasTag("APIMap") then
			apiMap = require(instance)
			break
		end
	end
	if not apiMap then error("Could not find APIMap module.") end
else -- Game context.
	packets = CollectionService:GetTagged("Packets")[1]
	if not packets then error("Could not find packets module.") end
	packets = require(packets)
	
	apiMap = packets.GetAPIMap:Fire()
end

-- Options defaults.
local defaults = require(data.Defaults)

-- Shared types.
local types = require(data.Types)

-- Signal type.
type Signal = types.Signal

-- Internal tween type.
type InternalTween = types.InternalTween & {
	Updated: Signal<number>?,
	Started: Signal?,
	Stopped: Signal?,
	Completed: Signal?,
}

-- Active tweens collection.
local tweens: {InternalTween} = {}

-- Tween functions.
local function stop(tween: InternalTween)
	-- Verify playback state.
	if not tween.Playing then return end
	
	-- Set playing boolean.
	tween.Playing = nil
	
	-- Tween removal.
	local lastIndex = #tweens
	local index = tween.Index
	if index == lastIndex then
		tweens[lastIndex] = nil
	else
		local last = tweens[lastIndex]
		last.Index = index
		tweens[index] = last
		tweens[lastIndex] = nil
	end
	
	-- Set time markers.
	tween.StopTime = os.clock()
end
local function destroy(tween: InternalTween)
	-- Disconnect destroy connection.
	tween.DestroyConnection:Disconnect()
	
	-- Ensure no playback.
	if tween.Playing then
		-- Tween removal.
		local lastIndex = #tweens
		local index = tween.Index
		if index == lastIndex then
			tweens[lastIndex] = nil
		else
			local last = tweens[lastIndex]
			last.Index = index
			tweens[index] = last
			tweens[lastIndex] = nil
		end
		
		-- Fire stopped signal.
		tween.Stopped:Fire()
	end
	
	-- Destroy signals.
	tween.Updated:Destroy()
	tween.Started:Destroy()
	tween.Stopped:Destroy()
	tween.Completed:Destroy()
	-- Clear tween data.
	table.clear(tween)
	-- Unlink methods.
	setmetatable(tween, nil)
end

local function start(tween: InternalTween, startOverride)
	-- Verify playback state.
	if tween.Playing then return end
	
	-- Set playing boolean.
	tween.Playing = true
	
	-- Handle conflicts.
	local instance = tween.Instance
	local values = tween.Values
	
	for _, otherTween in tweens do
		if otherTween.Instance ~= instance then continue end
		
		for value in otherTween.Values do
			if values[value] then
				stop(otherTween)
				if otherTween.Stopped then otherTween.Stopped:Fire() end
				tweens[otherTween] = nil
				break
			end
		end
	end
	
	-- Set time markers.
	local stopDuration = os.clock() - tween.StopTime
	if not startOverride then tween.StartTime += stopDuration end
	if tween.Interval then tween.LastUpdate = -math.huge end
	if tween.WaitTime then tween.WaitTime += stopDuration end
	tween.StopTime = nil
	
	-- Add tween.
	table.insert(tweens, tween)
	tween.Index = #tweens
end

-- Setup tween processing.
do
	local connection = (if plugin then RunService.Heartbeat else RunService.PreSimulation):Connect(function()
		if #tweens == 0 then return end
		
		local currentTime = os.clock()
		for _, tween in tweens do
			-- Ensure desired interval (specified in FPS).
			if tween.Interval then
				if currentTime - tween.LastUpdate < tween.Interval then continue end
				tween.LastUpdate = currentTime
			end
			
			-- Account for wait.
			if tween.WaitTime then
				if currentTime - tween.WaitTime < tween.DelayTime then continue end
				tween.WaitTime = nil
				tween.StartTime = currentTime
			end
			
			-- Calculate progress and update values.
			local alpha = (currentTime - tween.StartTime)*tween.InverseTweenTime
			
			local phaseCompleted = alpha >= 1
			
			if phaseCompleted then
				if tween.Reverse then alpha = 0 else alpha = 1 end
				
				for _, update in tween.UpdateFunctions do update(alpha) end
			else
				if tween.Reverse then alpha = 1 - alpha end
				
				local easedAlpha = tween.Ease(alpha)
				for _, update in tween.UpdateFunctions do update(easedAlpha) end
			end
			
			-- Fire updated signal with raw alpha.
			local updateSignal = tween.Updated
			if updateSignal then updateSignal:Fire(alpha) end
			
			-- Phase completion stuff.
			if phaseCompleted then
				if tween.Reverse then -- Already going in reverse. Means reversing is enabled, so no need to check for that.
					tween.Repetitions += 1
					if tween.RepeatCount == -1 or tween.Repetitions < tween.RepeatCount then
						if tween.DelayTime then tween.WaitTime = currentTime end
						tween.StartTime = currentTime
						tween.Reverse = nil
					else
						if not tween.StopTime then
							stop(tween)
							if updateSignal then -- If there's one signal, we know there are all of them.
								tween.Stopped:Fire()
								tween.Completed:Fire()
							end
						end
					end
				else -- Not going in reverse.
					tween.Repetitions += 1
					if tween.Reverses then
						-- Reversing enabled.
						if tween.DelayTime then tween.WaitTime = currentTime end
						tween.Reverse = true
						tween.StartTime = currentTime
					else
						-- Reversing disabled.
						if tween.RepeatCount == -1 or tween.Repetitions < tween.RepeatCount then
							if tween.DelayTime then tween.WaitTime = currentTime end
							tween.StartTime = currentTime
						else
							if not tween.StopTime then
								stop(tween)
								if updateSignal then -- If there's one signal, we know there are all of them.
									tween.Stopped:Fire()
									tween.Completed:Fire()
								end
							end
						end
					end
				end
			end
		end
	end)
	
	if plugin then
		plugin.Unloading:Connect(function()
			connection:Disconnect()
		end)
	end
end

-- Tween class.
local Tween = {}
Tween.__index = Tween

Tween.Start = function(tween: InternalTween)
	if not tween.StopTime then return end
	start(tween)
	tween.Started:Fire()
end
Tween.Stop = function(tween: InternalTween)
	if tween.StopTime then return end
	stop(tween)
	tween.Stopped:Fire()
end
Tween.Reset = function(tween: InternalTween)
	if not tween.StopTime then
		stop(tween)
		tween.Stopped:Fire()
	end
	tween.WaitTime = nil
	tween.StopTime = 0
	tween.StartTime = 0
	tween.Repetitions = 0
	tween.Reverse = nil
	for _, reset in tween.ResetFunctions do reset() end
end
Tween.Destroy = destroy

-- Server tweening.
if packets then
	local serverTweens = table.create(256)
	
	local function serverDestroy(tween: InternalTween)
		-- Disconnect destroy connection.
		tween.DestroyConnection:Disconnect()
		
		-- Ensure no playback.
		if not tween.StopTime then
			-- Tween removal.
			local lastIndex = #tweens
			local index = tween.Index
			if index == lastIndex then
				tweens[lastIndex] = nil
			else
				local last = tweens[lastIndex]
				last.Index = index
				tweens[index] = last
				tweens[lastIndex] = nil
			end
		end
		
		-- Clear tween data.
		table.clear(tween)
		-- Unlink methods.
		setmetatable(tween, nil)
	end
	
	packets.CreateTween.OnClientEvent:Connect(function(identifier, instance, values, options)
		-- Argument errors.
		if not instance then if RunService:IsStudio() then error("Could not find instance on client.") end return end
		
		-- Handle values.
		local updateFunctions, resetFunctions = getUpdateFunctions(apiMap, instance, values)
		
		-- Create tween.
		local easingStyle = options[2]
		local tween = nil
		tween = {
			-- Handle instance destroy.
			DestroyConnection = instance.Destroying:Connect(function()
				serverDestroy(tween)
			end),
			
			-- Main arguments.
			Instance = instance,
			Values = values,
			
			-- Value functions.
			UpdateFunctions = updateFunctions,
			ResetFunctions = resetFunctions,
			
			-- Options.
			InverseTweenTime = options[1] or defaults.InverseTime,
			Ease = if easingStyle then
				if easingStyle == "Linear" then easingFunctions.Linear else easingFunctions[easingStyle][options[3]]
			else
				easingFunctions.Linear,
			DelayTime = options[4] or defaults.DelayTime,
			Reverses = options[5] or defaults.Reverses,
			RepeatCount = options[6] or defaults.RepeatCount,
			Interval = options[7] or defaults.Interval,
			
			-- Time markers.
			StartTime = 0,
			StopTime = 0,
			
			-- Trackers.
			Repetitions = 0
		}
		
		-- Store the tween with its given identifier.
		serverTweens[identifier] = tween
	end)
	
	packets.StartTween.OnClientEvent:Connect(function(identifier, runTime, repetitions)
		local tween = serverTweens[identifier]
		if not tween then return end
		
		if repetitions then
			tween.Repetitions = repetitions
			if tween.Reverses then
				tween.Reverse = if repetitions%2 == 1 then true else nil
			end
		end
		if tween.StopTime then
			if runTime then
				tween.StartTime = os.clock() - runTime
				start(tween, true)
			else
				start(tween)
			end
		end
	end)
	packets.StopTween.OnClientEvent:Connect(function(identifier)
		local tween = serverTweens[identifier]
		if not tween then return end
		
		if not tween.StopTime then stop(tween) end
	end)
	packets.ResetTween.OnClientEvent:Connect(function(identifier)
		local tween = serverTweens[identifier]
		if not tween then return end
		
		if not tween.StopTime then stop(tween) end
		for _, reset in tween.ResetFunctions do reset() end
	end)
	packets.DestroyTween.OnClientEvent:Connect(function(identifier)
		local tween = serverTweens[identifier]
		if not tween then return end
		
		serverDestroy(tween)
	end)
end

-- Local tween creation.
return function(instance, values, options)
	-- Argument errors.
	if typeof(instance) ~= "Instance" then error("Invalid instance.", 2) end
	if type(values) ~= "table" or not next(values) then error("Invalid values.", 2) end
	
	-- Handle values.
	local updateFunctions, resetFunctions = getUpdateFunctions(apiMap, instance, values)
	
	-- Handle options.
	if type(options) ~= "table" then options = {} end
	
	local tweenTime = options.Time
	if type(tweenTime) ~= "number" then
		tweenTime = defaults.InverseTime
	elseif tweenTime <= 0 then
		tweenTime = 0
	else
		tweenTime = 1/tweenTime
	end
	
	local ease = nil
	do
		local easingStyle = options.EasingStyle
		local easing = easingFunctions[easingStyle]
		if not easing then
			easingStyle = "Linear"
			easing = easingFunctions.Linear
		end
		if easingStyle == "Linear" then
			ease = easing
		else
			local easingDirection = options.EasingDirection
			ease = easing[easingDirection]
			if not ease then
				easingDirection = defaults.EasingDirection
				ease = easing[easingDirection]
			end
		end
	end
	
	
	local delayTime = options.DelayTime
	if type(delayTime) ~= "number" or delayTime <= 0 then
		delayTime = defaults.DelayTime
	end
	
	local reverses = options.Reverses
	if reverses == false then
		reverses = nil
	elseif reverses ~= true then
		reverses = defaults.Reverses
	end
	
	local repeatCount = options.RepeatCount
	if type(repeatCount) ~= "number" then
		repeatCount = defaults.RepeatCount
	elseif repeatCount < 0 then
		repeatCount = -1
	end
	
	
	local interval = options.FPS
	if type(interval) == "number" then
		interval = 1/interval
	end
	
	-- Create tween.
	local tween = nil
	tween = setmetatable({
		-- Handle instance destroy.
		DestroyConnection = instance.Destroying:Connect(function()
			destroy(tween)
		end),
		
		-- Signals.
		Updated = Signal(),
		Started = Signal(),
		Stopped = Signal(),
		Completed = Signal(),
		
		-- Main arguments.
		Instance = instance,
		Values = values,
		
		-- Value functions.
		UpdateFunctions = updateFunctions,
		ResetFunctions = resetFunctions,
		
		-- Options.
		InverseTweenTime = tweenTime,
		Ease = ease,
		DelayTime = delayTime,
		Reverses = reverses,
		RepeatCount = repeatCount,
		Interval = interval,
		
		-- Time markers.
		StartTime = 0,
		StopTime = 0,
		
		-- Trackers.
		Repetitions = 0
	}, Tween)
	
	-- Return tween.
	return tween
end